org: cgeisler
app: sentiment
service: sentiment
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1

plugins:
  - serverless-python-requirements
  - serverless-offline

functions:
  hello:
    handler: handler.handle
    events:
      - httpApi:
          path: /dairy/entry
          method: post
